package com.example.myapplication.data

import androidx.room.ColumnInfo
import androidx.room.Entity
import androidx.room.PrimaryKey

// TODO 1a: mark this class as a table named "posts"
@Entity(tableName = "posts")
data class Post(
    // TODO 1b: make id the primary key, generated by Room
    @PrimaryKey(autoGenerate = true)
    val id: Long = 0L,

    @ColumnInfo(name = "content")
    val content: String,

    // TODO 1c: name this column "created_at"
    @ColumnInfo(name = "created_at")
    val createdAt: Long = System.currentTimeMillis(),
)
